# Generated by Django 4.0.3 on 2022-04-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_category_article_about_article_author_article_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=65)),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='difficulty_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='difficulty_units',
        ),
        migrations.AddField(
            model_name='article',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artigos.difficulty'),
        ),
    ]
