# Generated by Django 4.0.3 on 2022-04-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0005_alter_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
