# Generated by Django 4.0.3 on 2022-05-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0009_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artigos.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(null=True, upload_to='articles/covers/%Y/%m/%d/'),
        ),
    ]
