# Generated by Django 4.0.3 on 2022-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0010_alter_article_category_alter_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, default='articles/covers/%Y/%m/%d/default_article_cover.jpg', null=True, upload_to='articles/covers/%Y/%m/%d/'),
        ),
    ]
